;;; Assignment 2
;; Write an incremental parser that can parse English language
;; sentences.  Feel free to be as creative as you would like to be in
;; devising the parser (there are no requirements for a particular
;; parsing algorithm other than that the parser be incremental and
;; take one word at a time).  You are allowed to use whatever
;; supporting software you'd like to use short of using an existing
;; parser.  You will have access to at least two corpora for training.
;; When you write the parser, allowing for dialogue-based and
;; context-based biasing of the parse (e.g., prepositional attachment)
;; and demonstrate how this bias changes the parsing result.
(ns ^{:doc "An incremental parser."
      :author "Jeremiah Via <jeremiah.via@gmail.com>"}
  snld.parser)

(def ^:dynamic *parse*)


;; Implement the CCG parser from class
;; http://www.aclweb.org/aclwiki/index.php?title=Combinatory_Categorial_Grammar
(defn app-fore [a b]
  )
(defn app-back [a b]
  )
(defn comp-fore [a b]
  )
(defn comp-back [a b]
  )
(defn type-fore [a b]
  )
(defn type-back [a b])

(def lexicon
  {"marcel"       ["NP"]
   "conjectured"  ["(S\\N)//NP"]   
   "and"          ["(X\\*X)*X"]
   "might"        ["(S\\NP)//VP"]
   "prove"        ["VP//NP"]
   "completeness" ["NP"]
   "andie"        ["NP"]
   "steve"        ["NP"]
   "loves"        ["(S\\NP)//NP"]})

(defrecord Atom [content])
(defrecord Functor [left func right])

(defn pprint-lexicon [lexicon]
  ;;TODO
  )

(def combinatory-rules
  [app-fore  app-back
   comp-fore comp-back
   type-fore type-back])


(defn shift [])
(defn reduce [])

(defn push [stack entry]
  (into [entry] stack))

(defn ppeek [stk]
  [(first stk) (second stk)])

(defn ppop [stk]
  (drop 2 stk))

(defn lexicalize [string]
  (vec string))

(defn parse [string]
  (loop [buf (lexicalize string) stk nil]
    (if (empty? buf) stk
        (recur (rest buf) (push stk (first buf)))  )))


;; '((SQ (VBP are)
;;      (NP (PRP you))
;;      (NP (RB there))
;;      (. ?)))

(defprotocol Application
  (forward  [a] "Forward application")
  (backward [a] "Backward application"))
(defprotocol Combination
  (forward  [a] "")
  (backward [a] ""))
(defprotocol TypeRaise
  (forward  [a] "")
  (backward [a] ""))

(defrecord NP [content])
(defrecord VPfNP [content])
(extend-type VPfNP
  Application
  (forward [a]
    ())
  (backaward [b]
    ()))


(def sents
  ['((:SQ (VBP are) (NP (PRP you)) (NP (RB there)) (. ?)))
   '((INTJ (AP yep)))
   '((SQ (MD can) (NP (PRP you)) (VP (VB hear) (NP (PRP me))) (. ?)))
   '((S (INTJ (AP yes)) (NP (PRP I)) (VP (MD can) (VP (VB hear) (NP (PRP you)))) (. .)))
   '((INTJ (UH okay)))
   '((FRAG (INTJ (UH okay)) (VP (ADVP (RB just)) (ADVP (RB anywhere)) (ADVP (RB like)) (VP (VBG starting) (PP (IN in) (NP (RB here))) (VP (VBG starting) (PP (IN in) (NP (RB there))))))))])

(def sentences
  ['((SQ (VBP are) (NP (PRP you)) (NP (RB there)) (. ?)))
   '((INTJ (AP yep)))
   '((SQ (MD can) (NP (PRP you)) (VP (VB hear) (NP (PRP me))) (. ?)))
   '((S (INTJ (AP yes)) (NP (PRP I)) (VP (MD can) (VP (VB hear) (NP (PRP you)))) (. .)))
   '((INTJ (UH okay)))
   '((FRAG (INTJ (UH okay)) (VP (ADVP (RB just)) (ADVP (RB anywhere)) (ADVP (RB like)) (VP (VBG starting) (PP (IN in) (NP (RB here))) (VP (VBG starting) (PP (IN in) (NP (RB there))))))))])

;; ((INTJ (UH okay)) )
;; ((INTJ (AP yes)) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH okay)) (ADVP (RB so)) (S (NP (PRP you)) (VP (VBP 're))) (VP (VBD started) (NP (EX there)))) )
;; ((INTJ (UH okay)) )
;; ((SQ (INTJ (UH okay)) (FRAG (XY wh-)) (SBARQ (WHADVP (WRB where)) (SQ (VBP are) (NP (PRP you)) (PP (IN at)))) (. ?)) )
;; ((S (INTJ (UH um)) (NP (PRP I)) (ADVP (RB st)) (VP (VBD entered) (NP (DT the) (JJ first) (NN room)))) )
;; ((S (FRAG (PP (NP (DT the) (JJ first) (NN room))) (: -)) (S (NP (EX there)) (VP (MD should) (VP (VB be) (ADVP (RB like)) (NP (DT a) (JJ wooden) (NN platform)))))) )
;; ((INTJ (UH yeah)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH uh)) )
;; ((S (S (NP (PRP I)) (VP (VBP guess))) (S (S (VP (VBI keep) (VP (VBG going) (ADVP (RB straight))))) (SQ (VP (VBP unless))) (NP (PRP you)) (VP (VBP see) (NP (NN anything))))) )
;; ((S (INTJ (INTJ (UH okay)) (INTJ (UH um))) (NP (PRP I)) (VP (VBP see) (NP (DT a) (JJ green) (NN box)) (PP (IN with) (NP (DT a) (NN one))) (PP (IN on) (NP (PRP it))))) )
;; ((SBAR (INTJ (UH okay)) (WHADVP (WRB where)) (S (VP (VBZ is) (NP (NP (DT that)) (VP (VBN located))) (PP (IN at)))) (. ?)) )
;; ((S (INTJ (UH um)) (FRAG (NP (PRP it)) (VP (VBZ 's))) (S (VP (VBN located) (NP (NP (RB right)) (PP (IN next) (NP (FRAG (TO to)) (DT the) (NN doorway))) (PP (IN on) (NP (DT the) (NN left)))) (PP (IN on) (NP (DT the) (NN floor)))))) )
;; ((PP (IN on) (NP (NP (DT the) (NN left)) (PP (IN of) (NP (DT the) (NN door)))) (. ?)) )
;; ((PP (INTJ (UH yeah) (UH uh)) (IN towards) (NP (DT the) (JJ second) (NN room))) )
;; ((INTJ (UH okay)) )
;; ((NP (INTJ (UH yeah)) (NP (DT that) (NN doorway))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((INTJ (UH okay)) )
;; ((S (S (VP (VBI go) (PP (IN through) (NP (DT that) (NN doorway))))) (S (NP (PRP I)) (VP (VBP guess)))) )
;; ((NP (CC and) (ADVP (RB then)) (NP (NP (DT the) (JJ second) (JJ green) (NN box)) (NP (NP (DT the)) (NP (NN number) (CD two))))) )
;; ((INTJ (UH yeah)) )
;; ((FRAG (INTJ (UH um)) (VP (VBZ is) (PP (IN on) (NP (DT the) (JJ second) (NN step))) (PP (IN of) (NP (DT the) (JJ wooden) (NN platform))))) )
;; ((INTJ (UH okay)) )
;; ((PP (IN in) (NP (DT the) (JJ next) (NN room))) )
;; ((SQ (INTJ (UH okay)) (FRAG (XY what)) (SQ (VP (VBZ is) (NP (NP (NP (PRP it) (: -)) (PP (IN on) (NP (DT the) (NN left)))) (CC or) (NP (DT the) (NN right))))) (. ?)) )
;; ((S (NP (PRP it)) (VP (VBZ 's) (PP (IN on) (NP (DT the) (NN left))))) )
;; ((INTJ (UH okay)) )
;; ((NP (INTJ (UH mhm)) (NP (FRAG (DT the) (: -)) (INTJ (UH yeah)) (PP (IN on) (NP (DT the) (JJ second) (NN step))))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((FRAG (NP (PRP I)) (VP (VBP guess)) (INTJ (UH uh))) )
;; ((INTJ (UH okay) (UH oh)) )
;; ((S (S (ADVP (RB so)) (NP (PRP I)) (VP (VBD went) (PP (IN through) (NP (DT some)))) (: -)) (S (NP (PRP I)) (VP (VBD went) (PP (IN through) (NP (DT the) (JJ second) (NN room))))) (INTJ (RB right)) (. ?)) )
;; ((INTJ (CC and) (UH um)) )
;; ((S (ADVP (RB then)) (NP (PRP I)) (VP (VBD turned) (ADVP (RB right)) (PP (IN into) (NP (DT a) (JJ small) (NN room))))) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH um)) (CC and) (NP (DT the) (JJ third) (JJ green) (NN box)) (VP (VBZ is) (PP (IN on) (NP (DT a) (NN chair))))) )
;; ((PP (IN on) (NP (DT a) (NN chair)) (INTJ (RB there) (. ?))) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH uh)) )
;; ((S (INTJ (UH okay) (ADVP (RB so))) (VP (VBI exit) (NP (DT that) (NN room)))) )
;; ((SQ (VBP do) (NP (PRP you)) (VP (VB have) (NP (NP (DT a) (NN chair)) (PP (IN on) (NP (DT the) (NN map))))) (. ?)) )
;; ((INTJ (UH er)) )
;; ((S (INTJ (AP yep)) (FRAG (NP (PRP I)) (VP (VBP 've))) (S (VP (VBD got) (NP (PRP it))))) )
;; ((S (S (VP (VP (ADVP (RB so)) (VBI go) (ADVP (RB ahead))) (CC and) (VBI exit) (NP (DT that) (NN room)))) (CC and) (S (VP (VBI go) (PP (IN into) (NP (DT the) (JJ next) (NN room))))) (S (NP (PRP I)) (VP (VBP guess)))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((S (NP (PRP you)) (VP (MD should) (VP (VB be) (PP (IN in) (NP (NP (NP (DT a) (NN room)) (PP (IN with) (NP (NNS desks)))) (FRAG (CC and))))))) )
;; ((INTJ (UH um)) )
;; ((FRAG (INTJ (UH yeah) (UH okay)) (NP (DT the) (INTJ (UH uh)) (ADVP (RB fourth)) (NN book)) (S (NP (PRP I)) (VP (VBP turn) (PP (IN into) (NP (NP (DT the) (JJ first) (NN room)) (PP (IN on) (NP (DT the) (NN right)))))))) )
;; ((INTJ (AP yeah)) )
;; ((S (INTJ (UH uh)) (NP (DT the) (JJ fourth) (NN box)) (VP (VBZ is) (PP (IN on) (NP (NP (NN top)) (PP (IN of) (FRAG (DT the))))))) )
;; ((NP (NP (JJ filing) (NN cabinet)) (PP (IN on) (NP (DT the) (NN left)))) )
;; ((PP (IN on) (NP (DT the) (JJ left) (NN hand) (NN side)) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH mhm) (UH well)) (VP (VBI let) (S (VP (VBZ 's) (VP (VB see)))))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((SBARQ (ADVP (RB so)) (WHADVP (WRB where)) (SQ (VBP are) (NP (PRP you)) (FRAG (IN at) (ADVP (RB now)))) (. ?)) )
;; ((S (FRAG (DT the) (: -)) (ADVP (RB so)) (S (NP (PRP I)) (VP (VBD went) (ADVP (RB back)) (PP (IN into) (NP (NP (DT the) (JJR bigger) (NN room)) (PP (IN with) (NP (DT the) (NN desk)))))))) )
;; ((INTJ (UH yes)) )
;; ((INTJ (UH right)) )
;; ((INTJ (UH um)) )
;; ((PP (IN on) (NP (NP (DT the) (NN bookshelf)) (PP (IN in) (NP (NP (DT the) (NN corner)) (PP (IN of) (NP (DT the) (NN room))))))) )
;; ((INTJ (AP yes)) )
;; ((SINV (PP (INTJ (UH uh)) (IN on) (NP (DT the) (JJ bottom) (NN shelf))) (VP (VBZ is) (NP (DT the) (JJ fifth) (NN box)))) )
;; ((PP (IN on) (NP (DT the) (JJ right) (CC or) (NP (JJ left) (NN hand)) (NP (NN side))) (. ?)) )
;; ((PP (IN on) (NP (DT the) (JJ right) (NN hand) (NN side))) )
;; ((S (NP (DDT that)) (VP (VBZ 's) (NP (DT the) (JJ fifth) (NN box))) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH okay)) )
;; ((FRAG (INTJ (UH um)) (CC and) (ADVP (RB then)) (PP (IN in) (NP (DT the) (JJ second) (NN room)))) )
;; ((NP (NP (DT the) (JJ second) (NN room)) (INTJ (UH uh)) (NP (DT the) (JJ second) (JJ small) (NN room)) (. ?)) )
;; ((NP (INTJ (UH yeah)) (NP (DT the) (JJ second) (JJ small) (NN room))) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH um)) (NP (DT the) (JJ sixth) (NN box)) (VP (VBZ is))) )
;; ((FRAG (ADVP (RB right)) (IN inside) (XY t-) (PP (TO to) (NP (DT the) (NN left))) (NP (FRAG (IN of)) (DT the) (NN doorway))) )
;; ((PP (TO to) (NP (NP (DT the) (NN left)) (PP (IN of) (NP (DT the) (NN doorway))))) )
;; ((INTJ (UH mhm)) )
;; ((FRAG (INTJ (UH uh)) (NP (PRP it)) (VP (VBZ 's) (ADVP (RB against)) (NP (NP (DT the) (NN wall)) (CC or) (SBAR (WHADVP (WRB where)) (S (NP (DT the) (NN door)) (VP (VBZ opens)))))) (. ?)) )
;; ((FRAG (INTJ (UH um)) (NP (ADVP (RB against)) (DT the) (NN wall))) )
;; ((INTJ (UH okay)) )
;; ((S (NP (DDT that)) (VP (VBZ 's) (NP (NN number) (CD six))) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((FRAG (INTJ (UH oh)) (CC and) (S (NP (EX there)) (VP (VBZ 's) (NP (JJR more))))) )
;; ((S (INTJ (UH okay) (UH uh)) (ADVP (RB so)) (NP (PRP I)) (VP (VBD went) (PP (IN through) (NP (NP (DT the) (JJ big) (NN room)) (PP (ADVP (RB again)) (IN into) (NP (DT the) (NN hallway))))))) )
;; ((S (INTJ (UH okay)) (NP (PRP I)) (VP (VBP see) (NP (DDT that)))) )
;; ((S (INTJ (UH um)) (CC and) (NP (DT the) (JJ seventh) (NN box)) (VP (VBZ is) (PP (IN on) (NP (NP (DT the) (NN stack)) (PP (IN of) (NP (NNS chairs))))))) )
;; ((PP (IN on) (NP (NP (DT the) (NN stack)) (PP (IN of) (NP (NNS chairs)))) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((S (S (INTJ (UH uh)) (VP (VBP are) (RB there) (NP (CD three) (NNS stacks)))) (PP (IN of) (NP (NNS chairs))) (. ?)) )
;; ((INTJ (UH um)) )
;; ((FRAG (XY or)) )
;; ((S (INTJ (UH oh)) (FRAG (XY th-)) (NP (INTJ (UH well) (UH okay)) (NP (NP (DT the) (NNS chairs)) (PP (IN on) (NP (DT the) (NN left)))) (NP (NP (DT the)) (ADVP (JJS farthest) (PP (TO to) (NP (DT the) (NN left))))))) )
;; ((NP (NP (DT the) (NN furthest)) (PP (TO to) (NP (DT the) (NN left))) (. ?)) )
;; ((INTJ (AP yes)) )
;; ((S (NP (PRP it)) (VP (VBZ 's) (PP (IN on) (NP (DT that) (NN one)) (INTJ (UH okay))))) )
;; ((INTJ (UH yeah)) )
;; ((S (NP (DDT that)) (VP (VBZ 's) (NP (NN number) (CD seven)))) )
;; ((INTJ (UH okay)) )
;; ((SQ (VBZ is) (NP (DDT that)) (NP (NN number) (CD seven)) (. ?)) )
;; ((INTJ (AP yes)) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH uh)) (VP (VBI continue) (ADVP (RB around)))) )
;; ((INTJ (UH uh)) )
;; ((NP (DT that) (NN hallway)) )
;; ((S (FRAG (INTJ (UH okay)) (NP (PRP I)) (VP (VBD walked) (PP (IN through) (NP (DT the) (NN hallway))))) (S (INTJ (UH um)) (VP (VBD turned))) (ADVP (RB right))) )
;; ((S (CC and) (NP (DT the) (JJ eighth) (NN box)) (VP (VBZ is))) )
;; ((INTJ (UH hhh)) )
;; ((PP (PP (IN on) (NP (DT the) (NN left))) (PP (IN in) (NP (DT the) (NN corner))) (. ?)) )
;; ((INTJ (UH okay)) )
;; ((S (NP (ADVP (RB so)) (DT the) (NN hallway)) (VP (VBZ turns) (NP (NP (NN left)) (PP (IN at) (NP (DT this) (NN point)))))) )
;; ((INTJ (AP yes)) )
;; ((PP (CC but) (RB right) (PP (IN before) (PRN (NP (PRP it)) (VP (VBZ turns) (NP (DT the) (JJ eighth) (NN box)) (ADVP (RB right) (RB there)))) (ADVP (RB against)) (NP (DT the) (NN wall)))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((S (CC and) (ADVP (RB then)) (NP (PRP it)) (VP (VBZ turns))) )
;; ((S (NP (PRP I)) (VP (VBP think) (SBAR (S (NP (DDT that)) (VP (VBZ 's) (NP (DT the) (NN end)))))) (INTJ (RB right)) (. ?)) )
;; ((SINV (PP (INTJ (UH oh)) (TO to) (NP (DT the) (NN left)) (INTJ (UH okay))) (VP (VBI hold) (PRT (IN on)) (ADVP (RB just)) (NP (DT a) (NN second)))) )
;; ((SQ (INTJ (UH uh)) (FRAG (XY y-)) (SQ (VBP are) (NP (PRP you)) (PP (IN at) (NP (DT the) (JJ dead) (NN end)))) (. ?)) )
;; ((INTJ (AP yes)) )
;; ((NP (INTJ (UH uh)) (DT the) (JJ dead) (NN end)) )
;; ((S (S (INTJ (UH uh)) (NP (EX there)) (VP (MD should) (VP (VB be)))) (INTJ (UH uh))) )
;; ((S (FRAG (VP (VBZ looks) (NP (ADVP (RB like)) (DT a) (JJ brown) (NN box)) (PP (IN for) (PRN (VP (VBG collecting) (NP (DT the) (NN cardboard) (NNS blocks)))) (PP (INTJ (UH er)) (IN for) (NP (FRAG (IN for)) (DT the) (NNS blocks)))))) (VP (VBI pick) (NP (DDT that)) (PRT (RP up)))) )
;; ((INTJ (UH right)) )
;; ((S (S (NP (PRP I)) (VP (VBP see) (NP (DT the) (NN cardboard) (NN box)))) (INTJ (UH okay))) )
;; ((SQ (VBP do) (NP (PRP you)) (VP (VB see) (NP (DT the) (JJ blue) (NN box)) (ADVP (RB there))) (. ?)) )
;; ((S (NP (EX there)) (VP (VBZ 's) (NP (DT a) (JJ blue) (NN box))) (INTJ (RB here)) (. ?)) )
;; ((PP (IN at) (NP (DT the) (NN end)) (. ?)) )
;; ((S (INTJ (AP yeah)) (NP (EX there)) (VP (MD should) (VP (VB be) (NP (CD one)) (PP (IN in) (NP (NP (NP (DT the) (NN corner)) (PP (IN on))) (INTJ (UH uh)) (: -) (SBAR (IN if) (S (NP (PRP you)) (VP (VBP 're) (VP (VBG facing) (NP (DT the) (NN barrier))))) (. ?))))))) )
;; ((S (INTJ (UH uh)) (NP (PRP it)) (VP (MD should) (VP (VB be) (PP (IN on) (NP (PRP$ your) (JJ right) (NN hand) (NN side))) (PP (IN in) (NP (DT the) (NN corner)))))) )
;; ((S (NP (PRP I)) (VP (VBP do) (RB n't) (VP (VB see) (NP (DT a) (JJ blue) (NN box))))) )
;; ((FRAG (INTJ (UH uh)) (VP (VBP do) (RB n't) (VP (VB see) (NP (CD one)) (ADVP (RB anywhere))))) )
;; ((S (INTJ (INTJ (UH okay) (UH well)) (INTJ (UH uh))) (NP (PRP I)) (VP (VBP guess) (SBAR (S (NP (DDT that)) (VP (VBZ 's) (NP (NP (CD one)) (PP (IN of) (NP (DT the) (JJ false) (NNS ones)))) (PP (IN on) (NP (DT the) (NN map)))))))) )
;; ((S (ADVP (RB so)) (NP (PRP I)) (VP (VBP guess) (SBAR (S (VP (VP (VBI turn) (ADVP (RB around))) (CC and) (VP (VP (VBP go) (ADVP (RB back))) (INTJ (UH uh)) (NP (NP (DT the) (NN way)) (SBAR (S (NP (PRP you)) (VP (VBD came)))))))))) (CC and) (S (VP (VBI let) (S (NP (PRP me)) (VP (VBP know) (SBAR (WHADVP (WRB when)) (S (NP (PRP you)) (VP (VBI turn) (NP (PRP$ your) (JJ first) (NN corner)) (ADVP (RB left)))))))))) )
;; ((INTJ (UH okay)) )
;; ((SBAR (WHADVP (WRB when)) (S (NP (PRP I)) (VP (VBP turn) (VP (VBN left)))) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH um)) )
;; ((S (S (INTJ (UH okay)) (NP (PRP I)) (VP (VBD turned) (ADVP (RB right)) (ADVP (RB now)))) (S (NP (PRP I)) (VP (VBP 'm) (VP (VBG turning) (ADVP (RB left)))))) )
;; ((INTJ (UH um)) )
;; ((S (NP (EX there)) (VP (VBZ 's) (NP (DT a) (JJ blue) (NN box)) (PP (IN on) (NP (NP (DT a) (NN stack)) (PP (IN of) (NP (NNS boxes))))))) )
;; ((PP (IN on) (NP (NP (DT a) (NN stack)) (PP (IN of) (NP (NNS boxes)))) (. ?)) )
;; ((S (INTJ (AP yes)) (VP (VBI get) (NP (DT that) (NN one)))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((FRAG (CC and) (FRAG (VP (VB empty) (NP (DT the) (NNS blocks)))) (ADVP (RB right)) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((S (NP (PRP I)) (VP (MD 'll) (VP (VB look) (PP (IN for) (NP (NP (DT any) (JJ other) (NNS ones)) (SBAR (IN as) (S (NP (PRP you)) (VP (VBP 're) (VP (VBG walking))))))) (ADVP (RB back))))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((S (NP (EX there)) (VP (VBZ 's) (NP (DT another) (NN one)) (PP (IN on) (NP (DT the) (NN chair))))) )
;; ((PP (IN on) (NP (DT the) (NN chair)) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((INTJ (UH okay)) )
;; ((PP (INTJ (UH um)) (IN on) (NP (DT the) (JJ middle) (NN chair))) )
;; ((PP (IN on) (NP (DT the) (JJ middle) (NN chair))) )
;; ((INTJ (UH oy)) )
;; ((S (INTJ (UH okay)) (NP (DDT that)) (VP (VBZ 's) (FRAG (PRP it)))) )
;; ((S (FRAG (VBI hold) (NP (FRAG (IN on)) (ADVP (RB just)) (NP (DT a) (JJ second)))) (S (VP (VBI stay) (ADVP (RB right)) (ADVP (RB there))))) )
;; ((INTJ (UH okay)) )
;; ((S (VP (VBI stay) (ADVP (RB right)) (SBAR (WHADVP (WRB where)) (S (NP (PRP you)) (VP (VBP are)))))) )
;; ((INTJ (UH okay)) )
;; ((S (INTJ (UH uh)) (NP (ADVP (RB so)) (DT the) (NN goal)) (VP (VBZ has) (VP (VBN changed) (NP (DT a) (NN bit))))) )
;; ((SQ (INTJ (UH uh)) (FRAG (WRB how) (JJ many) (JJ yellow) (XY box-)) (SBARQ (WHNP (WRB how) (JJ many) (JJ yellow) (NNS blocks)) (SQ (VBP do) (NP (PRP you)) (VP (VB have)))) (. ?)) )
;; ((INTJ (UH okay)) )
;; ((NP (CD two)) )
;; ((NP (CD two)) )
;; ((INTJ (UH okay)) )
;; ((S (VP (VBI go) (ADVP (RB back)) (PP (TO to) (NP (NP (DT the)) (NP (DT the) (NN barrier)) (DT the) (JJ dead) (NN end))) (SBAR (WHADVP (WRB where)) (S (NP (PRP you)) (VP (VBD picked) (PRT (RP up)) (NP (DT the) (NN cardboard) (NN box))))))) )
;; ((S (VP (VBI go) (ADVP (RB back) (PP (TO to)))) (: -)) )
;; ((INTJ (RB quickly)) )
;; ((S (FRAG (NP (PRP we)) (VP (VBD got) (NP (CD three))) (: -)) (NP (PRP we)) (VP (VBD got) (NP (CD three) (NNS minutes)))) )
;; ((INTJ (UH quickly) (UH oh)) )
;; ((S (VP (VBI pick) (PRT (RP up)) (NP (NN what))) (. ?)) )
;; ((INTJ (AP yes)) )
;; ((S (INTJ (UH uh)) (VP (VBI go) (ADVP (RB back)) (PP (TO to) (NP (FRAG (DT the)) (ADVP (RB back)) (PP (TO to) (NP (DT the) (NN corner))))))) )
;; ((INTJ (UH yes)) )
;; ((SQ (VBP do) (NP (PRP you)) (VP (VB see) (NP (DT that) (JJ pink) (NN box))) (ADVP (RB there)) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((PP (IN at) (NP (DT the) (JJ dead) (NN end)) (. ?)) )
;; ((S (SBAR (FRAG (VBI put) (NP (CD one)))) (: -) (S (VP (VBI put) (NP (CD one)) (PP (IN of) (NP (NP (NP (DT the) (JJ yellow) (NNS blocks)) (PP (IN in) (NP (RB there)))) (PP (IN at) (NP (DT the) (JJ dead) (NN end)))))))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((FRAG (CC and) (FRAG (IN as) (S (NP (PRP you)) (VP (VBP come)))) (ADVP (RB back))) )
;; ((INTJ (UH uh)) )
;; ((S (S (INTJ (UH uh)) (VP (VBI go) (ADVP (RB back)) (SBAR (IN until) (S (NP (PRP you)) (VP (VBP see) (NP (NP (DT the) (JJ next) (JJ pink) (NN box)) (SBAR (WHNP (WDT which)) (S (VP (MD should) (VP (VB be))))))))))) (INTJ (UH uh)) (S (NP (PRP I)) (VP (VBP guess)))) )
;; ((PP (ADVP (RB right)) (IN before) (NP (DT the) (NN corder))) )
;; ((NP (PRP$ your) (JJ right) (NN hand) (NN side)) )
;; ((INTJ (UH yeah)) )
;; ((INTJ (UH yeah)) )
;; ((S (S (ADVP (RB then)) (VP (VBI go) (ADVP (RB ahead)))) (CC and) (S (VP (VBI put) (NP (CD one)) (PP (IN in) (NP (EX there)))))) )
;; ((S (ADVP (RB now)) (NP (DDT that)) (VP (VBZ 's) (NP (NP (NP (DT all)) (PP (IN of) (NP (PRP them)))) (RRC (S (NP (PRP you)) (VP (VBP have)))))) (INTJ (RB right)) (. ?)) )
;; ((INTJ (AP yeah)) )
;; ((NP (PDT all) (DT the) (JJ yellow) (NNS blocks) (. ?)) )
;; ((INTJ (RB so)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (AP yes)) )
;; ((FRAG (IN so) (INTJ (UH uh))) )
;; ((S (ADVP (RB now)) (VP (VBI go) (ADVP (RB back)) (PP (TO to) (NP (NP (NP (NP (DT the) (NN room)) (PP (IN with) (NP (DT the) (CD three) (NNS chairs)))) (CC or) (DT the) (NN part)) (PP (IN of) (NP (NP (DT the) (NN hallway)) (PP (IN with) (NP (DT the) (CD three) (NNS chairs))))))))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH um)) )
;; ((SBAR (WHNP (WRB when)) (FRAG (PRP you))) )
;; ((INTJ (UH uh)) )
;; ((S (VP (VBP enter) (NP (NP (DT that) (NN hallway)) (SBAR (IN as) (S (NP (PRP you)) (VP (VBP 're) (VP (VBG going) (ADVP (RB back)) (PP (IN into) (FRAG (DT the) (XY de-)) (NP (NP (DT the) (NN room)) (PP (IN with) (NP (DT all) (JJ th) (NNS chairs)))))))))))) )
;; ((PP (CC and) (IN in) (NP (NP (DT the)) (FRAG (XY de-)))) )
;; ((INTJ (UH mhm)) )
;; ((S (INTJ (UH uh)) (NP (EX there)) (VP (MD should) (VP (VB be) (NP (DT a) (JJ blue) (NN box)) (PP (IN on) (NP (DT that) (NN cart) (: -) (PP (IN on) (NP (DT the) (NN computer) (NN cart))))) (PP (IN in) (NP (NP (NN front)) (PP (IN of) (NP (PRP you)))))))) )
;; ((INTJ (UH okay)) )
;; ((PP (IN if) (SBAR (S (ADVP (RB so)) (VP (VBI get) (NP (NP (NP (DT the) (NNS blocks)) (ADVP (RB out))) (PP (IN of) (NP (EX there)))))))) )
;; ((SQ (VBP do) (NP (PRP I)) (VP (VB need) (NP (NP (DT all)) (PP (PP (IN of) (NP (DT the) (NNS blocks))) (CC or) (ADVP (RB just)) (NP (DT the) (JJ yellow) (NNS ones))))) (. ?)) )
;; ((INTJ (UH yeah)) )
;; ((S (ADVP (RB just)) (INTJ (UH well)) (NP (PRP I)) (VP (VBP 'm) (ADJP (RB pretty)) (ADJP (JJ sure)) (PP (NP (NNS blocks))))) )
;; ((S (ADVP (RB just)) (VP (VBI pick) (PRT (RP up)) (NP (PDT all) (DT the) (NNS blocks)))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH uh)) )
;; ((S (S (S (INTJ (UH uh)) (FRAG (IN if) (S (NP (PRP you)) (VP (VBP go) (PP (IN into) (NP (DT that) (JJ first) (JJ small) (NN room)))))) (: -)) (S (NP (DDT that)) (VP (MD would) (VP (VB be) (PP (IN on) (NP (PRP$ your) (JJ right) (NN hand)))))) (: -)) (INTJ (UH er)) (NP (PRP$ your) (JJ left) (NN hand) (NN side))) )
;; ((S (INTJ (UH uh)) (NP (EX there)) (VP (MD should) (VP (VB be) (FRAG (XY sh-)) (NP (NN door)))) (. .)) )
;; ((INTJ (UH okay)) )
;; ((S (S (VP (VBI wait))) (S (VP (VBI hold) (PRT (IN on)))) (S (NP (PRP I)) (VP (MD can) (RB n't) (VP (VB hear) (NP (PRP you)))))) )
;; ((SQ (FRAG (NN one)) (SQ (VP (MD should) (VP (VB be) (PP (IN by) (NP (DT the) (NN door)))) (NP (CD one) (JJ blue) (NN box))))) )
;; ((PP (IN behind) (NP (DT the) (NN door)) (. ?)) )
;; ((FRAG (XY ye-)) )
;; ((INTJ (UH okay)) )
;; ((S (CC and) (VP (VBZ is) (NP (EX there)) (NP (NP (NP (DT another) (NN one)) (PP (IN on) (NP (NP (NN top)) (PP (IN of) (NP (DT a) (NN desk)))))) (CC or) (NP (DT a) (NN chair)) (. ?)))) )
;; ((PP (IN in) (NP (DT that) (NN room))) )
;; ((INTJ (UH um)) )
;; ((PP (IN in) (NP (DT this) (NN room)) (. ?)) )
;; ((INTJ (AP yes)) )
;; ((PP (IN in) (NP (DT the) (JJ small) (NN room)) (. ?)) )
;; ((INTJ (AP no)) )
;; ((INTJ (UH okay)) )
;; ((S (NP (EX there)) (VP (VBZ 's) (NP (NP (DT no) (NNS chairs)) (CC or) (NP (NNS desks)) (CC or) (NP (NN anything))))) )
;; ((S (INTJ (UH okay)) (VP (VBI exit) (NP (DT that) (NN room)))) )
;; ((S (CC and) (VP (VBI go) (PP (IN into) (NP (DT the) (JJ next) (JJ small) (NN room))))) )
;; ((INTJ (UH okay)) )
;; ((PP (INTJ (UH okay)) (IN near) (NP (NP (DT the) (NN platform)) (CC or) (SBAR (S (PP (IN on) (NP (DT the) (NN desk))) (NP (EX there)) (VP (MD should) (VP (VB be) (NP (DT anothe) (JJ blue) (NN box)))))))) )
;; ((INTJ (UH oh) (UH okay)) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH alright)) )
;; ((INTJ (UH uh)) )
;; ((SQ (VBD did) (NP (PRP you)) (VP (VB go) (ADVP (RB back)) (PP (IN into) (NP (NP (DT the) (NN room)) (PP (IN with) (NP (PDT all) (DT the) (NNS desks)))))) (. ?)) )
;; ((PP (IN in) (NP (NP (NP (DT the)) (PP (TO to) (NP (EX there)))) (FRAG (MD should)) (PP (IN on) (FRAG (PRP$ your)))) (INTJ (UH uh))) )
;; ((INTJ (UH yeah)) )
;; ((S (INTJ (JJ left)) (FRAG (NN wall)) (NP (PRP you)) (VP (MD should) (VP (VB see) (NP (NP (DT a) (NN desk)) (PP (IN with) (NP (NP (CD two) (NNS chairs)) (PP (IN on) (NP (EX there)))))))) (. ?)) )
;; ((S (NP (EX there)) (VP (MD might) (VP (VB be) (NP (NP (DT a) (JJ blue) (NN box)) (PP (IN under) (NP (NP (NN one)) (PP (IN of) (NP (DT the) (NNS chairs))))))))) )
;; ((INTJ (UH mhm)) )
;; ((S (NP (PRP I)) (VP (VBP see))) )
;; ((INTJ (UH okay)) )
;; ((INTJ (UH oh)) )
;; ((S (FRAG (VBZ time) (NP (PRP 's)) (: -)) (S (VP (VBI time) (NP (PRP 's)) (PRT (RP up))))) )
;; ((S (INTJ (UH okay)) (S (NP (EX there)) (VP (VBZ 's))) (ADVP (RB also))) )
;; ((S (NP (PRP I)) (VP (VBP think) (PP (NP (DT the) (NN time))) (FRAG (VBZ 's)) (PRT (RP up)))) )
;; ((INTJ (UH what) (. ?)) )
;; ((INTJ (UH oh)) )
;; ((S (INTJ (UH uh)) (VP (VBI hold) (PRT (RP on)))) )
;; ((S (S (NP (PRP I)) (VP (VBP guess))) (S (VP (VBI come) (ADVP (RB back))))) )
